### ISSUE TITLE
Imagen de Python

### ISSUE THREAD

**Issue by JZylber** [nachovigilante/cheatsheets#11]
La imagen de Python tiene el color de fondo incorrecto. Hay que reemplazarla con una transparente con las dimensiones apropiadas para que no se deforme.

**Comment by nachovigilante** [comment]
No es más necesario luego del commit [8d2a31e](https://github.com/nachovigilante/cheatsheets/commit/8d2a31ef99e7a0a07d7da2ec2b3e6c38b4916c0c)
